framework/deproxy_server.py, helpers/deproxy.py, helpers/prepare.py, helpers/remote.py, long_body/test_response_wrong_length.py, prepare.py, regression/test_srv_failovering.py, run_tests.py, sched/test_http.py
Due to the polling cycle, creating new connection can be performed before removing old connection.
So we can have case with expected + 1 amount of connections. It's not a error case, it's a problem of polling
=> Allow 33 connections for deproxy server

framework/deproxy_manager.py, framework/deproxy_server.py, framework/tester.py
If we have exception during polling function, lock.release() doen't called. This PR fixes it and handles exceptions
=> Fix eternal waiting for lock in case of exception

leaks/test_leak.py, malformed/test_malformed_headers.py, malformed/test_malformed_structure.py, mixed_requests/test_mixed.py, pipelining/test_pipelining.py, selftests/test_framework.py
Don't use directives like 
```
vhost default {
proxy_pass default;
}
```
or `listen 80;`. There no need to repeat defaults in tests or explicitly add directives which should be implicitly created. Even worse, explicit definitions may shadow bugs with implicit generation.
=> Remove explicit directives if they can be implicitly created

cache/test_cache_deception_attack.py, tests_disabled.json
`tempesta_ip` stands for ip address of the Tempesta node,
`general_ip` - is for tests framework node.
Deproxy server is started on framework node, not on the same node Tempesta is started.
=> Fix failed tests from #59: use correct ip address to connect Tempesta to backend server

helpers/dmesg.py
It turned out the current version of `DmesgOopsFinder` is not precise enough. It tries to cut everything before line with substring "Start test" in it. But none of the tests I tried, push such line to the kernel buffer. In that case the whole output of `dmesg` was used. That makes a single line with "ERROR" substring to mark all subsequent tests as failed.
We can remove that fallback, but then there is no way to determine which parts of the log to take based only on the log contents anyway. However, we know that we need only the part that appeared after the moment `DmesgOopsFinder` is constructed.
The code in the patch polls output of `dmesg -w` to extract only lines we are interested in.
=> helpers: try to get exact lines from dmesg that appeared during a test

long_body/test_request_wrong_length.py
In tempesta-tech/tempesta#1141 flag  TFW_HTTP_SUSPECTED is removed, so when client sends invalid request and connection is to be closed, header `Connection: close` is set. Previous behaviour was to preserve `Connection:` header value,  so `Connection: keep-alive` or no header may be received  by client.
=> Expect 'Connection: close' header, when the connection is about to be closed

normalization/__init__.py, normalization/test_http_multipart.py
Adds tests for the recently added `http_post_validate` configuration parameter and its functionality.
=> add Content-Type header field normalization tests

framework/deproxy_server.py, helpers/deproxy.py
Fix #92 
**UPD**
Initial fix was wrong. Actually there was two attempts to fix the problem: one - in 281de6c1c9dc823cc5163f8a1cfabae171ea72aa by changing base class of `ServerConnection` from `asyncore.dispatcher_with_send` to `asyncore.dispatcher` and in previous version of this patch by forcing `ServerConnection.socket` to be synchronous. Fist attempt was mistakenly incomplete, but second was absolutely unneeded. 
The issue was in the `ServerConnection.send_response()` function. After N requests are responded the server connection may be closed. The function is very simple:  send response and close the connection.  But actual things is little bit different: only part of response may be sent: up to 512 bytes if `ServerConnection` is derived from  `asyncore.dispatcher_with_send`  or some …
=> fix #92. Ensure all data was sent before close server connection

helpers/__init__.py, helpers/control.py, helpers/util.py, testers/functional.py, testers/stress.py
Assert that a client in stress test actually did some work.
Fix ugly assertion 'False is not true'.
Print warnings on higest verbose level about deprecated classes (#56).
=> Small improvements in stress testing.

helpers/deproxy.py
ssl.SSLWantReadError may be thrown if a client receives only part of a TLS record spanning over multiple TCP segments. As the whole TLS record wasn't received yet, its decryption doesn't start. We need to try again with more data, later.
Turns out, Tempesta prefers to pack as much data into TLS records as it can. So they often are sent in multiple packets, increasing chances to encounter `ssl.SSLWantReadError`.
(related: https://github.com/tempesta-tech/tempesta/issues/1283)
=> explicitly ignore ssl.SSLWantReadError, it's expected to happen

helpers/dmesg.py, msg_sequence/test_pairing.py, tls/handshake.py, tls/test_tls_cert.py, tls/test_tls_handshake.py
Do not change sysctl net.core.message_cost by default in DmesgFinder.
Switch of net ratelimiting only for local context instances of the class
when we sure that Python GC frees the instance on return, failed assertion,
or unhandled exception.
Use TempestaTest.oops when we don't need our own instance of DmesgFinder().
=> Do not change sysctl net.core.message_cost by default in DmesgFinder.

tests_disabled.json
https://github.com/tempesta-tech/tempesta/issues/1283 is now closed, so it's time to enable those tests again.
=> enable tests disabled because of #1283

tls/handshake.py, tls/test_tls_cert.py, tls/test_tls_handshake.py
Tests and Tempesta can be started on the same or on the different nodes.
When different nodes are used, tests can't use local ip address (127.0.0.1)
and must query current Tempesta address from configuration file.
=> use correct remote host address when establishing TLS handshake

tls/handshake.py
https://github.com/tempesta-tech/tempesta/issues/1324
Usually it’s enough for us to send TLS records, which is done through self.sock.sendall(), but in that place the code explicitly translates the record into a string, divides it into pieces and sends it in pieces. This requires direct access to the socket.
=> fix sending chunked tls request

tls/test_tls_integrity.py
Deproxy client is confused when its `.responses` array length changes. Which can cause false positives if the same client instance is used for more than one request-response pair.
`DeproxyClient.wait_for_response` [expects](https://github.com/tempesta-tech/tempesta-test/blob/5ee7af2a091ccf2c5e2bbe5a1333b418dc72eeff/framework/deproxy_client.py#L176) `self.responses` length to be in sync with `self.valid_req_num`.
=> keep client.responses array length intact

tests_disabled.json, tls/test_tls_handshake.py
Add test on sending close_notify alert on close_notify alert and enable tests disabled because of https://github.com/tempesta-tech/tempesta/issues/1308
=> add test by close_notify alert and enable tests disabled because of #1308

helpers/dmesg.py, msg_sequence/test_pairing.py, tls/test_tls_cert.py, tls/test_tls_handshake.py
Some tests are expected to generate messages (dmesg), but sometimes rate limiter hides them, making tests spuriously fail. Let's selectively disable ratelimiting for some tests explicitly.
=> turn dmesg ratelimiting off when some messages are expected for checking

tests_disabled.json, tls/test_tls_handshake.py
fix tempesta-tech/tempesta#1347
We do not send sni, the tls connection will be open using a global certificate (vhost1), and vhost will be selected by the host header
=> if we do not send sni, vhost will be selected by the host header

leaks/test_leak.py
- replace 2 get_memory_line() calls with 1 get_memory_lines() call
- to calculate the used memory you do not need to know the total memory
- using exceptions instead of error codes
- don`t took pagecache memory into account used memory
=> don`t took pagecache memory into account used memory

tests_disabled.json
Enable fuzzing test since issues at https://github.com/tempesta-tech/tempesta/issues/1318 are fixed now.
=> enable tls.test_tls_handshake.TlsHandshakeTest.test_fuzzing

long_body/test_response_wrong_length.py, sessions/test_js_challenge.py
4 tests failed on CI:
- `long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength`: after recent changes TempestaFW never adds `Content-Length` header and always transforms message to chunked encoding, but the test expected the old behaviour. Fixed that. And removed a dead code.
- `sessions.test_js_challenge*` - A JS challenge template was supposed to be copied from `srcdir` to `workdr`, but instead of copying on `tempesta` node, the framework tried to copy file from `framework` to `tempesta` node. In local installations both nodes are the same virtual machine, so it worked, but on CI - two different, thus the copy operation failed. But there was one issue more: the `libtemplate-perl` package was absent on `tempesta` node and the template couldn't be processed.
With this fixes …
=> Fix minor tests issues

tls/test_tls_cert.py
RFC 8422 5.1.1 deprecates curves 1..22 (the indexes are defined in RFC 4492 5.1.1), so SECP192r1 was completely removed from Tempesta TLS and certificates can not be loaded any more.
This is a test change for https://github.com/tempesta-tech/tempesta/pull/1363
=> secp192r1 certificates can not be loaded any more

framework/tester.py, testers/functional.py, testers/stress.py, tls/test_tls_cert.py
=> tls: ERROR messages in kernel log are expected on configuration errors

README.md, framework/__init__.py, framework/client.py, framework/external_client.py, framework/tester.py, h2/__init__.py, h2/test_h2_specs.py, helpers/remote.py, helpers/tempesta.py, tests_config.ini.sample
Run h2spec utility against Tempesta and evaluate return code. Increase
debug level to get h2spec detailed results.
A new directive in `tests_config.ini` under section `[Client]` may be
required since h2spec is never available through pacage manager and
need to be installed from https://github.com/summerwind/h2spec :
h2spec = /path/to/h2spec
Fix tempesta-tech/tempesta#739
=> Add basic h2 proto tests

sessions/test_cookies.py
Now test is able to catch degradation described in tempesta-tech/tempesta#1401
=> sticky cookie: check redirected location and fail test if it's mismatched

tls/test_tls_cert.py
Changes according to https://github.com/tempesta-tech/tempesta/pull/1375
=> SECP521 has been removed from Tempesta TLS

frang/test_http_resp_code_block.py
https://github.com/tempesta-tech/tempesta/issues/1441
Test for `block_action attack reply` according to which, when the limiits is exceeded, a 403 response should come
=> Test for `block_action attack reply`

sessions/test_js_challenge.py, sessions/test_redir_mark.py, tests_disabled.json
https://github.com/tempesta-tech/tempesta/issues/1398
- adding tests for blocking when the number of redirected requests is exceeded and resetting the counter of redirected requests after a timeout during which the client must block if the number of redirected requests is exceeded
- creating a base class for JS challenge
- test on enable JS Challenge after reload
=> Tests on sticky cookies and JS challenge

check_deps/check_cmds_nodes.py, framework/client.py, h2/test_h2_headers.py, h2/test_h2_specs.py, tests_config.ini.sample
https://github.com/tempesta-tech/tempesta/issues/1408
=> Test on correctness of serving short/long headers

tls/__init__.py, tls/test_tls_kernel.py
Test for problems like https://github.com/tempesta-tech/tempesta/issues/1340
The test doesn't reveal the original problem on the faulty kernel version, but it's make sense to have some kernel crypto testing anyway.
=> Test for the Linux kernel crypto routines

sessions/test_cookies.py, sessions/test_js_challenge.py, sessions/test_learn.py, sessions/test_redir_mark.py, sessions/test_sessions.py, tests_disabled.json
Inheriting for named vhosts and for implicit default vhost -- two different implementations, so need to test both.
Tests for tempesta-tech/tempesta#1460
=> sessions: add tests to check that sticky configuration can be inherited

h2/test_h2_headers.py
https://github.com/tempesta-tech/tempesta/pull/1461
When placed in the cache and when converted to h2, header names must be transformed to lowercase, otherwise curl will return a non-zero return code tests will fail
=> Test for converting header names to lowercase when converting response to h2

README.md, helpers/tf_cfg.py, tests_config.ini.sample
Some tests use `${general_ip}` as an address where deproxy's server is listening, but that option wasn't mentioned in `tests_config.ini.sample`.
=> add description of ${general_ip} and set its default value

tls/test_tls_cert.py
https://github.com/tempesta-tech/tempesta/issues/1335 deprecates the curve while the test suite already has the test for unsupported secp521, so just remove the test for secp384.
See commit https://github.com/tempesta-tech/tempesta/commit/3a8d8c5e6b46a68dfefcbd6bff1135749ef5f601
=> Remove test for secp384

http_rules/test_http_tables.py
https://github.com/tempesta-tech/tempesta/issues/1453
=> Tests on block_action

h2/test_h2_perf.py, tls/test_tls_limits.py
With https://github.com/tempesta-tech/tls-perf/commit/11392a1da6f7cf715a624ebcb0efcb4b47af1e43fixing https://github.com/tempesta-tech/tls-perf/issues/9, by default tls-perf uses any ciphersuite, so add ECDHE-ECDSA-AES128-GCM-SHA256 explicitly in each tls-perf call to adjust the previous behavior.
=> tls-perf: specify ECDHE-ECDSA-AES128-GCM-SHA256 explicitly

cache/test_cache_control.py, http_rules/test_http.py, http_rules/test_http_tables.py
Fixes [tempesta-tech/tempesta#1544](https://github.com/tempesta-tech/tempesta/issues/1544)
Functional tests for cookie rule: matching part (field name and value) and action.
Matching part tests in test_http_tables tests and `$cache` action tests in test_cache_control_tests.
All test tasks from linked issue are done.
Signed-off-by: Aleksey Mikhaylov <aym@tempesta-tech.com>
=> Functional tests for cookie http_chain rules

http_rules/test_http_tables.py, tests_disabled.json
Added tests according to #214's description and disabled a test for an abstract base class.
As for now with Tempesta from [this](https://github.com/tempesta-tech/tempesta/pull/1628) branch:
```
root@nick-vm:~/tempesta-test# ./run_tests.py http_rules.test_http_tables
...
----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------
.s..........F....
======================================================================
FAIL: test_chains (http_rules.test_http_tables.HttpTablesTestMarkRules)
----------------------------------------------------------------------
File "/root/tempesta-test/http_rules/test_http_tables.py", line 373, in test_chains …
```
=> Tests for configuration variables in custom redirects.

tests_disabled.json
Long body have 2 tests which leads to FAIL condition:
long_body.test_long_request.RequestTest1M
long_body.test_long_request.RequestTest1k
```
[12199.646174] [tempesta fw] Warning: Parser error: state=RGen_BodyInit input(-8)=0xa('0.0.1
[12199.646175] [tempesta fw] Warning: failed to parse request: 127.0.0.1
```
Tests:
long_body.test_long_response.ResponseTest1k
long_body.test_long_response.ResponseTest1M
also was disabled by another issue
I think we have a problems with tempesta-fw parser which leads to test fails
=> long_body works fine except RequestTests

tests_disabled.json, very_many_backends/test_deadtime_1M.py
There is no fix
VM tempesta-test configuration changed for corresopnd current config
Also warning `Too much (4096) workers requested. Only 16 is possible` fixed by set workers count to 16
=> enable many_backends

README.md, framework/client.py, h2/test_h2_specs.py, tests_disabled.json
Now that we have `--exclude` flag in our `h2spec` fork, we can gracefully
disable some failing `h2spec` tests.
=> disable failing `h2spec` tests

framework/client.py, helpers/remote.py, http2_general/test_h2_specs.py
Now I believe we fully mitigated the vast majority of the issues that caused framework hang-ups.
Note, that there are still rare cases when tests will hang up due to some yet undiscovered bugs in Tempesta, usually those are indicated by `dmesg` warnings. This is 1) out of the scope of this PR, 2) simply suppressing errors is quite the opposite of our goal for testing, which is finding bugs, hence in those cases dedicated Tempesta issues have to be filed.
=> Properly handle errors that happen on external binary clients execution

http2_general/test_h2_specs.py
After adding [tests](https://github.com/tempesta-tech/h2spec/pull/3) to `h2spec` covering Stream ID values, the test that is supposed to ensure that Stream ID values are not reused is failing for about 2 out of 10 times. 
This behavior is always reproduced in the same way. After starting Tempesta and running that test for the first time, there will be a trace in `dmesg` (which is basically the first bullet of https://github.com/tempesta-tech/tempesta/issues/1387):
```
[Thu Aug 25 17:54:48 2022] ------------[ cut here ]------------
[Thu Aug 25 17:54:48 2022] WARNING: CPU: 0 PID: 228365 at /root/tempesta/fw/http.c:6495 tfw_http_msg_process_generic+0x409/0x670 [tempesta_fw]
[Thu Aug 25 17:54:48 2022] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) …
```
=> disable failing `h2spec` test

helpers/deproxy.py, selftests/test_responses.py
Now we try to determine end of chunked body before pass stream to parse_trailer and append the final CRLF to the body. When the final CRLF passed to parse_trailer, it will be dropped this implies chunked body without trailer will be invalid.
=> read_chunked_body: fixed chunked body trailer parsing

helpers/remote.py, requirements.txt
Can't run tests in isolated framework mode.
For Python3, `RemoteNode.wait_available` is never completes successfully:
- `RemoteNode.run_cmd` returns tuple of `bytes`, because subprocess stream is not in text mode: https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate
- `RemoteNode.wait_available` bytes to str comparison `b"check" != "check"` is always False (was True for Py2)
=> Fix remote node availability check

framework/client.py, framework/external_client.py, selftests/test_framework.py, tests_disabled.json
I fixed the issue with get results for the 'wrk' client. 
I changed the expectations of clients 'wrk' and 'curl'. Now we wait for end of life for client process.
I added 'wrk' and 'curl' client work tests to 'selftests' and enabled them.
=> "wrk" does not receive results

framework/client.py, multiple_listeners/test_mixed.py, multiple_listeners/test_multiple_listening.py, multiple_listeners/test_on_the_fly.py, selftests/test_framework.py
The problem of hangs is described in [Programming guidelines](https://docs.python.org/3/library/multiprocessing.html#programming-guidelines). I changed expectation for curl and wrk client, but because of [multithreading/multiprocessing semantics](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.empty) we should not receive data from a queue before calling the `stop()` method.
=> fixing large data hangs in stdout

cache/test_cache.py, http_rules/test_http_tables.py, tests_disabled.json
These tests aim to ensure that Tempesta generates correct static responses in most common use-cases using `h2` protocol.
=> add `h2` static responses tests

frang/__init__.py, frang/test_http_conn_limits.py, tests_disabled.json
https://github.com/tempesta-tech/tempesta/issues/1649#event-7411842458
The burst of connections is taken into account in the 125 ms quantum. Curl is pretty heavy for this so we use deproxy.
=> functional tests for connection_rate and connection_burst

framework/x509.py, helpers/dmesg.py, selftests/test_x509.py, tests_disabled.json, tls/test_tls_cert.py
Tests for #212 . All tests should pass for the current Tempesta FW version.
Changes to the framework:
- new `CertGnerator` field: `san` - Subject Alternative Name extension
-  new `DmesgFinder` method: `warn_match` - get list of occurrences of given string in system log.
=> Subject Alternative Name certificates

framework/client.py, framework/curl_client.py, framework/tester.py, selftests/test_curl_client.py, setup.sh, tests_config.ini.sample
Add new `framework.client.Client` for convenient work with the `curl` utility.
Client was used in #290, and now pulled into separate PR.
Client implementation includes:
- Setting the binary to be used, with the `Client.curl` config option
- Installed binary version check
- Log output for easier debugging
- Nice representation for client and response objects
- Response status and headers parsing
- Transfer information parsing (list of available variables: https://curl.se/docs/manpage.html#-w )
- URI and options addition during the tests
- Cookies support
- HTTP, HTTPS, HTTP/2 switch
- Parallel transfer mode switch
```python
clients = [
{
"id": "default",
"type": "curl",
},
{
"id": "ssl-head",
"type": "curl",
"ssl": True,
"addr": "${tempesta_ip}:8000",
"uri": "/page"
"cmd_args": (
" --head" …
```
=> Add CurlClient: wrapper to manage cURL

framework/deproxy_client.py
Just concatenate received body to local response body. Parsing of body will have no effect for HTTP2 frames. Content-Length also not required in HTTP2, therefore our standard logic can't be applied. Handling of TrailersReceived also incorrect, but it's not critical, now we don't have HTTP2 trailers in tempesta.
=> deproxy_h2: fixed receiving multiple DATA frames

cache/test_purge.py
**test_purge** by request:
miss, miss, hit, hit, purge, miss, miss, hit, hit
**test_purge_get_basic** by request:
miss, miss, hit, hit,	cache, hit, miss, hit
**test_purge_get_garbage** by request:
miss, hit, purge, miss, hit, purge, miss, hit
**test_purge_get_uncached** by request:
cache, hit
**test_purge_get_uncacheable** by request:
miss, hit, not cache (Cache-Control: private), miss, miss
=> Fix cache_misses

http2_general/test_h2_headers.py, http_general/__init__.py, http_general/test_headers.py, tests_disabled.json
HTTP and HTTP2 headers tests:
* `http_general.test_headers.BackendSetCoookie` — https://github.com/tempesta-tech/tempesta/issues/1690
* `http_general.test_headers.RepeatedHeaderCache` — https://github.com/tempesta-tech/tempesta/issues/1691
* `http2_general.test_h2_headers.MissingDateServerWithLargeBodyTest` — https://github.com/tempesta-tech/tempesta/issues/1704
Tests was used in https://github.com/tempesta-tech/tempesta-test/issues/290, and now pulled into separate PR.  
Currently failing tests are disabled.
=> HTTP headers tests set

cache/test_cache.py, cache/test_purge.py, tests_disabled.json
*  `cache.test_cache.TestChunkedResponse` — https://github.com/tempesta-tech/tempesta/issues/1698
* `cache.test_purge.TestPurgeGet` — https://github.com/tempesta-tech/tempesta/issues/1692
Tests was used in https://github.com/tempesta-tech/tempesta-test/issues/290, and now pulled into separate PR.
Currently failing tests are disabled.
=> Truncated cached responses tests

framework/deproxy_client.py, selftests/test_deproxy.py
This was used in #265, and now pulled into separate PR.
`handle_read()` method is call 3-4 (or more) times for 2xx responses, but only 1 times for 4xx responses.
=> fix: deproxy-h2 does not receive 4xx response

cache/test_cache_control.py, helpers/tf_cfg.py, http_rules/test_http.py, t_long_body/test_long_request.py, tests_disabled.json, tls/test_tls_kernel.py
I didn't fix `t_long_body.test_long_request` and `very_many_backends.test_deadtime_1M` because they are working on CI now. But I added curl error output for `test_long_request`.
The main problem of blinking `test_cache_control` is situation when `max-age` == `age`. I fixed timeouts for these tests.
`test_cache_control` are disabled  by https://github.com/tempesta-tech/tempesta/pull/1765.
=> fixed blinking tests

tests_disabled.json
After appropriate fix in tempesta we can enable this test.
=> Enable test_h2_double_different_forwarded_headers test

http2_general/test_h2_headers.py, tests_disabled.json
As we discussed - add a test, which cover multiple Set-Cookie headers case in HTTP2 version
=> Add BackendSetCoookieH2 test

tests_disabled.json
After fixed of #1690 issue in tempesta we enable all tests which was blocked by this issue. Note that
t_sites.test_wordpress.TestWordpressSiteH2 tests
are also blocked by 1669, so they are not enabled.
=> Enable tests which was blocked by #1690 tempesta issue

http2_general/test_h2_sticky_cookie.py, tests_disabled.json
After fixing of #1748 and #1396 issues in tempesta we enable all tests which was blocked by these issues. Also fixed some problems in tests:
=> Enable tests which was blocked by #1748 and #1396

framework/deproxy_client.py, helpers/deproxy.py, http2_general/__init__.py, http2_general/helpers.py, http2_general/test_flow_control_window.py, http2_general/test_h2_frame.py, http2_general/test_h2_headers.py, http2_general/test_h2_hpack.py, http2_general/test_h2_max_frame_size.py, http2_general/test_h2_streams.py, tests_disabled.json
Now deproxy h2 client can:
- send settings frame;
- update default settings before create connection;
- accept settings frame with ack flag;
- wait settings frame with ack flag;
- saves error codes;
- send bytes;
`handle_read` method for deproxy h2 client - now `method` variable is created when client receives `ResponseReceived` event. This fixes error of receiving frames other than headers.
Added tests for issue #88:
> Verification of correct frames exchange during establishing of h2 connection: get correct SETTINGS frame (with SETTINGS_INITIAL_WINDOW_SIZE parameter), correct WINDOW_UPDATE frame and correct SETTINGS ACK frame.
> [HPACK entries eviction](https://tools.ietf.org/html/rfc7541#section-4): we must correctly process the maximum dynamic table and evict old entries - the test …
=> h2 tests and deproxy h2 update

framework/deproxy_client.py, http2_general/test_h2_frame.py, http2_general/test_h2_hpack.py, tests_disabled.json
#88 
> Verification of correct handling for connection and stream error cases: a) get valid GOAWAY frame in response on connection error case; b) get valid RST_STREAM frame in response on stream error situation (the whole connection must remain alive).
I also added some tests for `header table size update` bytes in headers frame.
=> h2 tests for RST_STREAM and GOAWAY frames

framework/tester.py, http2_general/test_h2_responses.py, tests_disabled.json
There was a problem with response absence in case
of invalid http2 request. Implement  several tests with different invalid htt2 requests to cover this problem.
Some of these tests require fix of #1781 in tempesta! Since #1781 is reproduced only on CI we should run check this patch with appropriate branch (MekhanikEvgenii/Strange-warning-only-on-CI) several times.
=> Implement tests for #1794 issue in tempesta

framework/tester.py, helpers/remote.py, http2_general/test_h2_headers.py, http2_general/test_h2_specs.py, http2_general/test_h2_streams.py, tests_disabled.json
New tests:
- TE header in h2 request.
- issue #88
> Basic test for streams multiplexing: 1. Different HTTP/2 requests (i.e. HEADERS/CONTINUATION/DATA frames in each request) are sent in several streams - one by one, without waiting the responses; 2. And correct HTTP/2 responses must be received for each request/stream (regardless of the sending/receiving order). Do this in one and several TCP connections in parallel.
Added env variable for curl secrets.
=> h2 tests and update for h2spec

.pre-commit-config.yaml, helpers/control.py, helpers/tf_cfg.py, requirements.txt, tests_config.ini.sample
Added new directive `tmp_config` to config that allows to specify path name of tempesta's template config.
Currently template config generates to framework `workdir`
=> Add new directive `tmp_config` to config 

framework/deproxy_client.py, framework/tester.py, helpers/deproxy.py, helpers/tf_cfg.py, http2_general/test_h2_headers.py, http2_general/test_h2_hpack.py, http2_general/test_h2_stream_states.py, tests_config.ini.sample
Deproxy client can create IPv6 socket connection.
DeproxyClientH2 can wait to receive RST_STREAM.
=> update deproxy client and tests for stream states

framework/deproxy_client.py, http2_general/test_h2_hpack.py
In some tests we check raw response data, but previously in case when we receive not complete response we clear response buffer, so tests which check raw response data fails. Now a new field which collect all last response data was added.
=> Implement additional field to save raw response data

http2_general/test_h2_frame.py
3 seconds is not enought for getting response in case of MTU 80.
=> Increase time for waiting response.

access_log/common.py
Current requirement is too weak: 9 space-separated tokens. Also require some of that tokens to be enclosed into quotes to distinguish from other 9-word messages.
=> Improve access log lines extraction

t_frang/test_http_strict_host_checking.py
Since we decide that equality of forwarded host
and header host is not necessary, we should remove appropriate tests.
=> Remove some tests

framework/deproxy_client.py, helpers/deproxy.py
Now client does not wait for response if connection is closed. [CI with -T 1](http://tempesta-vm.cloud.cherryservers.net:8080/job/Run%20tests/661/parameters/)
=> DeproxyClient: updated `wait_for_response` method.

framework/deproxy_client.py
We can receive several data events and one of
it contains end_of_stream flag. We should not
increment flow control window for stream in
this case because stream is already closed.
=> Fix flow control in deproxy client

regression/test_stress_failovering.py, regression/test_stress_pipeline.py
When index page is missed in nginx directory regression tests fell because nginx returned 403 but test expects 200. Now nginx will return 200 for any request and index file doesn't need.
=> Fix regression tests

framework/tester.py, helpers/control.py, tls/test_tls_cert.py
We can't raise exceptions, because some tests intentionally leave Tempesta config empty. So just write warning.
=> Refix of empty Tempesta config problem

t_frang/__init__.py, t_frang/test_whitelist_mark.py, tests_disabled.json
This PR adds tests for `whitelist_mark` directive, ensuring that whitelisted requests skip frang.
- https://github.com/tempesta-tech/tempesta/issues/917
frang `connection_rate` for whitelisted requests is tested as described in
- https://github.com/tempesta-tech/tempesta/issues/1949
=> Add whitelist_mark test (917)

framework/parameterize.py, requirements.txt, t_frang/test_http_resp_code_block.py, t_frang/test_tls_incomplete.py
Function example:
```
from framework.parametrize import param, parameterize
@parameterize.expand([
param(name="first", param1=1, param2=2),
param("second", param1=2, param2=1),
param("third", 1, 1),
param("fourth", 1, param2=3),
])
def test(self, name, param1, param2)
...
```
Class example:
```
from framework.parametrize import parameterize_class
@parameterize_class([
{"name": "Http", "clients": [DEPROXY_CLIENT]},
{"name": "H2", "clients": [DEPROXY_CLIENT_H2]},
])
class TestResponse(tester.TempestaTest):
...
```
=> parameterization via decorators

t_frang/frang_test_case.py, t_frang/test_client_body_and_header_timeout.py, tests_disabled.json, tests_disabled_tcpseg.json
`client_header_timeout` and `client_body_timeout`
configuration options work in the following way:
When we receive the first block of the request
header or body, we remember the time when it was
received. When the next block arrives, we check
the time of its arrival and if the waiting timeout exceeds the specified one, we drop the request.
Fix tests according this description.
=> Enabled and fix tests blocked by #1762

framework/curl_client.py, selftests/test_curl_client.py, t_frang/test_whitelist_mark.py, tests_disabled.json
- Initialize netfilter rules before starting client (it is necessary for successful passing mark to tempesta).
- Increase timeout for parallel curl connections.
=> Enable and fix tests blocked by #1949

msg_sequence/test_pairing.py
#56 by @krizhanovsky 
The Pairing test suite rewrite with used `framework.tester.TempestaTest`
=> Rewrite pairing test

http2_general/test_h2_block_action.py, http2_general/test_h2_hpack.py, http2_general/test_h2_specs.py, tests_disabled_tcpseg.json
Also write tests to check that Tempesta send
error response with COMPRESSION_ERROR in case
if hpack table size is encoded in invalid place.
=> Enable test blocked by #1825

sessions/test_h2_sticky_scheduler.py
Fixed unstable test `sessions.test_h2_sticky_scheduler.H2StickySchedulerTestCase.test_h2_cookie_scheduler`.
Used the decorator `@dmesg.unlimited_rate_on_tempesta_node` that turns off dmesg messages rate limiting to ensure important messages are caught.
=> Quick fix flaky test

http2_general/test_h2_specs.py, tests_disabled.json, tests_disabled_remote.json, tests_disabled_tcpseg.json
Enable test blocked by 1824 and some other
tests which were blocked by fixed issues.
=> Enable tests according fixes in Tempesta

http2_general/test_h2_specs.py
Because test result considered as correct, enable it permanently.
=> Enable hpack/5.2/3 test.

http2_general/test_h2_specs.py
We should set block_action to drop for h2spec
tests, because otherwise we send response in case
of error, but some h2spec tests doesn't expect it.
=> Fix h2spec test config

t_reconf/test_stress_sched_dynamic.py, t_reconf/test_stress_sched_hash.py, t_reconf/test_stress_sched_ratio.py, t_regress/test_reboot_under_load.py, t_regress/test_stress_failovering.py, t_sched/test_hash_stress.py, t_sched/test_ratio_static.py, t_sched/test_ratio_weight.py, t_stress/test_stress.py
By default max_concurrent_streams is equal to 100, which is not enough for stress tests.
=> Increment max_concurrent_streams for stress tests

multiple_listeners/test_mixed.py
=> Add test for simultaneous HTTP/1.1 and HTTP/2 availability over HTTPS on a single port

t_reconf/test_reconf_base.py
=> t_reconf: Add test case for h2 and https coexistence on the same port

framework/tester.py, helpers/control.py, helpers/error.py, helpers/shell.py, run_config.py, run_tests.py, tests_disabled_dbgkernel.json
This option runs `kmemleak` check after all the tests
related to [23](https://github.com/tempesta-tech/tempesta-ci/issues/23) and [29](https://github.com/tempesta-tech/tempesta-ci/pull/29)
=> add the `kernel-dbg` option to `run_tests.py`

cache/test_purge.py, tests_disabled_remote.json, tests_disabled_tcpseg.json
Now Tempesta FW fails to start if cache directive is empty or equal to zero, but purge directive is set. Also Tempesta FW fails to start if purge directive is set but purge acl is not set and vice versa.
=> Implement tests to check Tempesta 'cache' directive

t_frang/test_config.py, tests_disabled_dbgkernel.json
Add tests to check reconiguration for `http_ct_vals` directive. This tests is very useful with kmemleak, because Tempesta FW had leak which was fixed and checked by this tests.
=> Add tests to check frang reconfiguration

t_regress/test_stress_failovering.py
Tests `test_failovering_sched_ratio` and
`test_failovering_sched_hash` can hung and crash
because of a lot of warning messages in dmesg.
We should suppress warnings for such tests.
=> Add decorator to suppress waringns

t_reconf/test_reconf_base.py
After removing appropriate warning message
from Tempesta FW, remove it from tests.
=> Remove searching warning in dmesg.

ws/test_ws_ping.py
It seems that we should use `unlimited_rate_on_tempesta_node` each time when we search some warning message in dmesg for test.
Closes #710
=> Fix flacky test

framework/deproxy_client.py, framework/lxc_server.py, selftests/test_deproxy.py
- deproxy_client.py - we must not use `STATE_STARTED` as `abort_cond` for `wait_for_connection_close` because `handle_close`, etc. can change the state (for example `handle_close` method change status: `STATE_STARTED` -> `STATE_STOPPED`). Then `wait_for_connection_close` will return None, but it is unexpected. So the `STATE_ERROR` state can be used as `abort_cond`;
- lxc_server.py sometimes needs more time to close on CI;
- rework `test_wait_for_headers_frame` test using a new option in DeproxyClientH2 - `auto_flow_control`.
=> fix unstable tests

framework/deproxy_auto_parser.py
Since PR2243 we don't add Content-Length to headers. Change tests accordingly.
=> Don't add Content-Length to expected headers for HTTP2

access_log/test_access_log.py, access_log/test_access_log_h2.py, t_sites/test_tempesta_tech.py, ws/test_ws_ping.py
In #537 access_log fields were changed. Instead of on|off fields there are dmesg|mmap|off. Change test configs accordingly.
=> Replace 'access_log on' by 'access_log dmesg'

cache/test_cache.py, framework/deproxy_server.py, framework/docker_server.py, helpers/analyzer.py, helpers/port_checks.py, helpers/remote.py, helpers/tf_cfg.py, setup.sh
Currently in test `TestCacheClean` we testing cache in REPLICA mode, therefore on numa machine cached
response will be copied to each node and in statistics we got total count of objects around all NUMA nodes.
`lscpu` added to setup.sh
=> Take into account NUMA nodes count in `TestCacheClean`

t_reconf/test_reconf_base.py
This test send 5 requests and uses `server.sleep_when_receiving_data = 1` for DeproxyServer which block `deproxy_manager` loop . Client sometimes require more time to receive responses.
=>  fix unstable test

selftests/test_lxc_server.py
```
test_wait_for_connections_negative (selftests.test_lxc_server.TestLxcServer) ... 25-01-26 13:34:12.208633 CRITICAL  | Exception in stopping process:                                                                                                    tf_cfg.py:258
process: <Popen: returncode: 1 args: 'lxc config device remove tempesta-site-stage te...>;                                                        
stderr: b"Error: Device doesn't exist\n", type: <class 'helpers.error.ProcessBadExitStatusException'>, traceback:                                 
Traceback (most recent call last):                                                                                                                
File "/home/jenkins/workspace/Manual_run/tempesta-test/framework/stateful.py", line 69, in …
```
=> fixed lxc container 9000 port conflicting with clickhouse

t_ja5/test_ja5t.py
```
FAIL: test_hash_for_client_not_block (t_ja5.test_ja5t.TestJa5tHttp)
----------------------------------------------------------------------
File "/home/jenkins/workspace/Manual_run/tempesta-test/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
return func(*(a + p.args), **p.kwargs, **kw)
File "/home/jenkins/workspace/Manual_run/tempesta-test/t_ja5/test_ja5t.py", line 129, in test
self.assertTrue(client.wait_for_response())
AssertionError: None is not true
```
=> fixed ja5t seg test failure

tests_disabled_tcpseg.json
```
======================================================================
FAIL: test_frang (t_access_log.test_access_log.AccessLogFrang)
----------------------------------------------------------------------
File "/home/jenkins/workspace/Manual_run/tempesta-test/t_access_log/test_access_log.py", line 213, in test_frang
self.assertTrue(msg is not None, "No access_log message in dmesg")
AssertionError: False is not true : No access_log message in dmesg
```
=> fixed t_access_log frang tests failure

ws/test_ws_ping.py
```
test (ws.test_ws_ping.WssStress) ... Task exception was never retrieved
future: <Task finished name='Task-4525' coro=<_wrap_awaitable() done, defined at /usr/lib/python3.10/asyncio/tasks.py:643> exception=OSError(98, "error while attempting to bind on address ('127.0.0.3', 8123): address already in use")>
File "/usr/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
return (yield from awaitable.__await__())
File "/home/jenkins/workspace/Manual_run/tempesta-test/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 1132, in __await_impl__
server = await self._create_server()
File "/usr/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] …
```
=> fixed busy 8123 port

t_ja5/test_ja5t.py, tests_disabled_tcpseg.json
```
======================================================================
FAIL: test_hash_for_client_not_block (t_ja5.test_ja5t.TestJa5tHttp)
----------------------------------------------------------------------
File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
return func(*(a + p.args), **p.kwargs, **kw)
File "/home/symstu/projects/tempesta/tempesta-test/t_ja5/test_ja5t.py", line 130, in test
self.assertTrue(client.wait_for_response())
AssertionError: None is not true
======================================================================
ERROR: test_Http (t_ja5.test_ja5t.TestJa5tStress)
---------------------------------------------------------------------- …
```
=> fixed unstable the ja5 stress test on seg

t_fault_injection/test_fault_injection_base.py
Previously there were several BUGs in Tempesta
when allocation fails during crypro context
creation. This tests check it.
=> Add error injection tests.

helpers/tf_cfg.py, t_frang/test_http_trailer_split_allowed.py
fix tests with trailers - Tempesta doesn't allow trailers for GET\HEAD requests.
fix config generation for clickhouse with remote setup.
=> fix config generation 

http2_general/test_h2_max_frame_size.py
We should not change H2Base `post_request`, otherwise it damage all other tests.
=> Fix `post_request` corruption

cache/test_cache.py, encoding/test_encoding.py, framework/deproxy_auto_parser.py, framework/deproxy_client.py, helpers/deproxy.py, http2_general/test_flow_control_window.py, http2_general/test_h2_frame.py, http2_general/test_h2_headers.py, http_general/test_headers.py, t_sites/test_tempesta_tech.py
test for https://github.com/tempesta-tech/tempesta/pull/2173
=> fix(1902): correct trailer headers placement

run_tests.py, t_malformed/test_h2_malformed_headers.py, t_malformed/test_malformed_headers.py
The test runner must not return 0 status when `expectedFailure` tests have `unexpected success` status.
=> fix returncode 0 for `unexpectedSuccesses` tests.

README.md
We can only use Python 3.10. Unfortunately, it's not possible to set up the test environment for Python 3.11.
=> The versions of the required dependencies have been fixed.

cache/test_cache.py
Tempesta FW should not save 'Age' response header in cache, during saving response in cache. But Tempesta FW should take it into account during satisfying the next request using this saved response. This tests check it.
=> Implement tests to check 'Age' header in response

t_frang/test_concurrent_connections.py, tests_disabled_remote.json, tests_disabled_tcpseg.json
Add test that verifies Tempesta applies frang limits only to socket listining by it.
=> feat: Add test verifies correctness of frang limits

framework/lxc_server.py, helpers/tf_cfg.py, selftests/test_lxc_server.py, setup.py, t_sites/test_tempesta_tech.py, t_stress/test_ddos.py, tests_disabled.json
- remove the starting and stopping lxc container, because it's require a lot of resources and time;
- now lxc container must be run first;
- rework setup.py for that (now lxc container uses 7000 port);
related to [PR49](https://github.com/tempesta-tech/tempesta-ci/pull/49)
=> rework start and stop method in lxc_server.py

encoding/test_encoding.py
Tempesta FW moves body during making headers if count of skb fragments is exceeded. Later Tempesta FW
removes flaged data from the body, so all pointers should be correct. Add special test for this case.
=> Add test to check moving body with transfer-encoding

t_fault_injection/test_fault_injection_base.py
New function `ss_skb_realloc_headroom` was implemented in Tempesta FW source code to be sure, that headroom of skb which is pushed in socket write queue is great or equal to MAX_TCP_HEADER. Add error injection tests to be sure that we gracefully handle situation when this function fails.
=> Implement new error injection tests.
