tempesta-tech/tempesta-test

- helpers/prepare.py
tcp_tw_recycle is removed in kernel 4.14
> remove tcp_tw_recycle

- helpers/control.py
https://github.com/tempesta-tech/tempesta/pull/967
> Fix number of connections

- testers/stress.py
It's just workaround. Real fix is required.
> Don't count 500 errors

- framework/tester.py
- helpers/control.py
- helpers/dmesg.py
- helpers/shell.py
- helpers/tf_cfg.py
- testers/functional.py
- testers/stress.py
fix: tempesta-tech/tempesta/issues/985
> Detect Oops, WARNING and Log start stop of tests to dmesg

- framework/deproxy_client.py
- framework/deproxy_manager.py
> Fix bad file descriptor on client connect

- framework/tester.py
- helpers/tempesta.py
- testers/functional.py
- testers/stress.py
fix: #21 
It looks wrong to remove all servers on reconfigure.
> don't create sg for empty server list

- helpers/control.py
> Remove redundant thread starting

- README.md
- cache/test_cache.py
- cache/test_cache_methods.py
- flacky_net/test_sockets.py
- framework/client.py
- framework/deproxy_client.py
- framework/deproxy_server.py
- framework/nginx_server.py
- health_monitoring/test_health_monitor.py
- helpers/chains.py
- helpers/control.py
- helpers/deproxy.py
- helpers/remote.py
- helpers/stateful.py
- helpers/tf_cfg.py
- http_rules/test_http.py
- long_body/test_response_wrong_length.py
- long_body/tester.py
- msg_sequence/test_pairing.py
- pipelining/test_pipelining.py
- reconf/test_stress_grace.py
- regression/test_invalid.py
- regression/test_shutdown.py
- run_tests.py
- sched/test_hash_func.py
- sessions/cookies.py
- sessions/test_sticky_sess.py
- very_many_backends/test_deadtime_1M.py
There are some typos in the code and text, that I'd like to be corrected.
> correcting assorted typos

- cache/__init__.py
- cache/test_cache_deception_attack.py
- tests_disabled.json
Detailed information in https://github.com/tempesta-tech/tempesta/issues/905 issue
> Test for web cache deception attack

- helpers/deproxy.py
- long_body/test_response_wrong_length.py
- msg_modification/__init__.py
- msg_modification/tests_encode_to_chunked.py
Here are tests for tempesta-tech/tempesta#639
> Add tests for message transformation

- check_deps/check_cmds_nodes.py
- check_deps/check_dependencies.sh
- check_deps/check_files_nodes.py
- check_deps/check_framework.sh
- check_deps/check_python_dependencies.py
Some text messages in dependency testing scripts looks wrong. This patch changes them to look better. At least for me.
Also fixes https://github.com/tempesta-tech/tempesta-test/issues/98.
> fix some typos in the dependency checking scripts

- tests_disabled.json
tempesta-tech/tempesta#1146 is fixed now, so enable the test
> Enable TLS stress test

- helpers/sysnet.py
- helpers/tempesta.py
- very_many_backends/test_deadtime_1M.py
No changes to logic of the test, just some fixes about calling and using functions.
> Fix minor errors that breaks tests

- tls/test_tls_cert.py
https://github.com/tempesta-tech/tempesta/issues/1333
> Signature algorithm and signature hash function have no restrictions

- tests_disabled.json
Enable chuncked tls tests for https://github.com/tempesta-tech/tempesta/pull/1348
> enable chuncked tls tests

- helpers/dmesg.py
- leaks/test_leak.py
- regression/test_reboot.py
- tls/handshake.py
- tls/test_tls_handshake.py
- tls/test_tls_integrity.py
There are some typos in the comments that I'd like to see fixed.
> fix typos found by spellintian

- tls/test_tls_handshake.py
During https://github.com/tempesta-tech/tempesta/issues/1318 investigations I found another issue, possibly related but not explicitly mentioned in https://github.com/tempesta-tech/tempesta/issues/1318 itself. To make it crash a custom MTU setting was needed. Not exactly a usable way to check in a automated way. So that particular sub-test was extracted to this PR. On my machine it triggers a WARN_ON each time I run it on an unfixed Tempesta revision, and completes successfully on a fixed revision.
> add a customized test case from the test_fuzzing

- sessions/test_js_challenge.py
- sessions/test_sessions.py
The test was missed in the #144 PR. Requires tempesta-tech/tempesta#1366
> Add js_challenge functional tests

- tls/test_tls_handshake.py
As Tempesta ignores remainder of the large ciphersuite lists, there should be no errors generated.
> tls: test_many_ciphers shouldn't expect an error

- sessions/test_js_challenge.py
Issue was introduced in a1f1d0579ad562dee38a157d52bac55ab886f1f8
> Fix  invalid indent preventing test to run

- h2/test_h2_headers.py
- h2/test_h2_specs.py
- malformed/test_malformed_headers.py
Functional tests for tempesta-tech/tempesta#1413
> Add tests for missing headers

- vhost/test_add_hdr.py
Implements cases addressed in tempesta-tech/tempesta#1457
> Add test cases for h1 response modification on serving from cache

- tls/test_tls_integrity.py
https://github.com/tempesta-tech/tempesta/issues/1431
https://github.com/tempesta-tech/tempesta/issues/1435
> Adding base tests on https

- access_log/__init__.py
- access_log/common.py
- access_log/test_access_log.py
- access_log/test_access_log_h2.py
> HTTP/1.x tests for access logging from tempesta/1567

- tls/handshake.py
- tls/test_tls_cert.py
- tls/test_tls_handshake.py
- tls/test_tls_limits.py
Follow tempesta-tech/tempesta#1521
Link tempesta-tech/tempesta#1511
> Fix poor connection error messages

- README.md
- requirements.txt
- setup.sh
Added:
paramiko
subprocess32
websockets
wrk
deproxy at this time has errors with pip installation method
> Add requirements

- framework/x509.py
removed excessive import, linting a bit
> removed excessive import, linting a bit

- access_log/test_access_log.py
- access_log/test_access_log_h2.py
- tests_disabled.json
Need to fix gen_cert for non localhost
> Access_log tests - works fine at localhost

- tests_disabled.json
Probably tests was disabled cause wrk wasnt installed
Now works fine
> mixed_request tests on

- http_rules/__init__.py
- http_rules/test_match_duplicated_headers.py
Test added to "http_rules" because crash happened on matching header by HTTP Tables.
> Added tests for crash in __http_msg_hdr_val  #1637

- access_log/test_access_log_h2.py
> Fix after 1650

- msg_modification/tests_encode_to_chunked.py
- tests_disabled.json
> Msg modification fix

- regression/test_invalid.py
- tests_disabled.json
> Regression tests

- tests_disabled.json
Removed duplicated disabled tests
Vhosts - uncommented cause works fine. Maybe after #1650 - 45/45 ok
> vhosts enabled + tests_disabled.json fix

- tests_disabled.json
> Disable DeproxyTestH2.test_bodyless_multiplexed

- tests_disabled.json
Just change reason for tls tests
> tls reason fix

- setup.sh
- tests_disabled.json
Changed related to https://github.com/tempesta-tech/tempesta/pull/1643 and Ubuntu 22
> Ubuntu 22 and 3 disabled tests

- tls/test_alpn_order.py
Add tests to ensure that a proper protocol gets picked up after ALPN.
> test ALPN protocol priority order

- http2_general/__init__.py
- http2_general/test_h2_ping.py
~~Note that currently all tests within `http2_general` directory pass for me and I've deleted a corresponding entry from `tests_disabled.json`. Please, whoever is going to review this PR, ensure that all those tests pass for you too.~~
> add `h2` ping test

- run_tests.py
I add parameter for future test running functional
Any criticism is welcome
> Add repeat parameter

- encoding/__init__.py
- encoding/test_encoding.py
In particular, this is follow up tests mentioned in https://github.com/tempesta-tech/tempesta-test/issues/298
> add a group of encoding-related tests

- helpers/shell.py
- selftests/__init__.py
- selftests/test_shell.py
> Fix load of empty tests_resume.json 

- tls/handshake.py
- tls/test_tls_handshake.py
Micro fix for test_1byte_transfer - its running out from 5 seconds
I suggest timeout property is needed
> TLSHandshake - self.timeout

- framework/deproxy_client.py
- selftests/test_deproxy.py
This was used in https://github.com/tempesta-tech/tempesta-test/pull/265, and now pulled into separate PR.
> fix: deproxy client does not start several times on local network (temporary solution)

- t_frang/test_tls_incomplete.py
Now Curl establishes parallel connection.
> fix: failures of `tls_incomplete_connection_rate` tests on CI

- tests_priority
- tests_retry
These changes fixup `daily tests` job and make framework a bit stable
> Mb test docker server priority

- sessions/test_learn.py
- sessions/test_sessions.py
http://tempesta-vm.cloud.cherryservers.net:8080/job/Run%20tests/470/console
> fix sessions tests

- cache/test_conditional.py
Since we should process unqouted Etag headers (many do not follow RFC and send Etag without double quotes), we should add test for this case.
> Add test for unqouted Etag header

- t_sites/test_wordpress.py
- tests_disabled.json
There were two problems:
1. Mark didn't clear.
2. Cache didn't purge.
> Fix TestWordpressSiteH2

- framework/deproxy_client.py
- helpers/__init__.py
- helpers/networker.py
- http2_general/test_flow_control_window.py
- http2_general/test_h2_frame.py
- http2_general/test_h2_specs.py
- http2_general/test_h2_stream_states.py
- tests_disabled.json
- tls/test_tls_integrity.py
Implement tests for framing with enabled/disabled tso, sro, dso and small mtu to check how new framing works.
> Implement tests for framing with enabled/disabled tso, sro, dso

- framework/deproxy_client.py
- framework/deproxy_server.py
- framework/tester.py
- tests_disabled_tcpseg.json
[CI](http://tempesta-vm.cloud.cherryservers.net:8080/job/Run%20tests/590/console)
> updated tests_disabled_tcpseg.json

- forwarding/test_match_host_forwarded.py
- http2_general/test_h2_headers.py
- http_general/test_headers.py
- t_frang/__init__.py
- t_frang/test_host_required.py
- t_frang/test_http_strict_host_checking.py
- t_frang/test_ip_block.py
- t_http_rules/test_h2_http_rules.py
- t_http_rules/test_http_rules.py
- tests_disabled.json
- tests_disabled_tcpseg.json
- tls/test_tls_cert.py
- tls/test_tls_limits.py
Tests on [CI](http://tempesta-vm.cloud.cherryservers.net:8080/job/Run%20tests/583/console) with [PR1862](https://github.com/tempesta-tech/tempesta/pull/1862)
> host parsing tests and fixed tests for PR 1862

- http2_general/test_h2_headers.py
- tests_disabled.json
See https://github.com/tempesta-tech/tempesta/issues/1736 for details
> Prepare test for duplicated cookie headers

- tests_disabled.json
> Re-enable tests disabled by #1805

- tests_disabled.json
Merge only after https://github.com/tempesta-tech/tempesta/pull/1895 is merged
> Enable split cookie test

- t_http_rules/test_h2_http_tables.py
- t_sites/test_wordpress.py
- tests_disabled.json
Related tempesta PR: https://github.com/tempesta-tech/tempesta/pull/1905
> Fix tests for #1841

- http2_general/test_h2_headers.py
- http2_general/test_h2_specs.py
- tests_disabled.json
Enable tests after merging https://github.com/tempesta-tech/tempesta/issues/1729
> Enable "capitalized headers" test

- tls/test_tls_cert.py
Implement special test with cert, which signed by
supported curve and key with unsupported curve.
> Implement test for secp192r1 curve

- selftests/test_deproxy.py
- t_frang/test_http_strict_host_checking.py
- t_http_rules/test_http_tables.py
- t_malformed/test_h2_field_validity.py
- tests_disabled.json
After 1819 we send 403 response if no appropriate virtual host is found and don't close connection.
> 1819 Follow

- helpers/tf_cfg.py
- run_tests.py
Be sure, that after merging this commit all related default parameters was changed (e.g. in Jenkins).
> Make --verbose parameter taking an argument.

- framework/deproxy_server.py
- helpers/deproxy.py
- t_frang/test_http_methods.py
- tests_disabled_tcpseg.json
After resolving #1872 issue in tempesta repository unblock appropriate tests.
> Unblock and fix tests blocked by 1872

- cache/test_cache.py
- cache/test_conditional.py
- cache/test_purge.py
- helpers/deproxy.py
- sessions/test_learn.py
- tests_disabled.json
- tests_disabled_remote.json
- tests_disabled_tcpseg.json
- tests_retry
Closes [810](https://github.com/tempesta-tech/tempesta/issues/810)
> cache tests v2

- t_modify_http_headers/test_common_config.py
- t_modify_http_headers/test_common_config_h2.py
- t_modify_http_headers/test_logic.py
Test for verifying correctness of modification `Host` header using `req_hdr_set` directive
> Test `req_hdr_set` for `Host` header

- framework/deproxy_client.py
- framework/deproxy_server.py
- framework/docker_server.py
- framework/nginx_server.py
- framework/port_checks.py
- framework/tester.py
- helpers/remote.py
- reconf/test_reconf_base.py
- tests_disabled.json
- tests_disabled_remote.json
- tests_disabled_tcpseg.json
depends on [2045](https://github.com/tempesta-tech/tempesta/pull/2045)
> on the fly configuration tests

- tests_disabled.json
After renaming reconf directory to r_reconf
we should do appropriate fix in tests_disabled.
> Hot fix tests_disabled.

- t_reconf/test_reconf_base.py
We need to check `conns_n` option for server in
server group because reconfiguration of this option leads to kenrel hung
> Implement test to check `conns_n` server option

- t_malformed/test_h2_malformed_headers.py
- t_malformed/test_malformed_headers.py
test adjustments for https://github.com/tempesta-tech/tempesta/pull/2088
> remove test cases using disallowed chars

- cache/test_cache.py
- cache/test_cache_methods.py
- tests_disabled.json
Also write more tests for caching responses for
POST request.
> Enable tests blocked by 1995.2

- framework/x509.py
- helpers/remote.py
- t_stress/test_nginx.py
> Create /tmp/tempesta folder automatically

- sessions/test_cookies.py
We need to check empty cookie_options and
js challenge directives and also we should
check how cookie_options work with domain option.
> Add extra tests for cookie options config

- tests_disabled.json
https://github.com/tempesta-tech/tempesta/pull/2095
> fix(1902): correct the skb len

- http2_general/test_h2_headers.py
- tests_disabled.json
for https://github.com/tempesta-tech/tempesta/pull/2125
> http2 tests with invalid headers in trailer

- tls/test_tls_cert.py
Tests for issue https://github.com/tempesta-tech/tempesta/issues/2156 . This test doesn't expose the problem, but I think it's worth testing one more ciphersuite
> Test for EC prime256v1 certificate with SHA384 signature

- t_stress/test_header_leak.py
> test OOM by header leak

- http2_general/test_h2_hpack.py
We have a BUG when Tempesta FW realloc hpack dynamic table, impment test to check fix.
> Write a test to check how we realloc hpack table

- tests_disabled.json
Because Issue #2084 fixed test passed successfuly.
> Enable "test_clear_client_connection_stats_greater"

- framework/deproxy_server.py
- http2_general/test_h2_responses.py
- t_fault_injection/test_fault_injection_base.py
- t_health_monitoring/test_health_monitor.py
- tests_disabled_tcpseg.json
Also implement tests to check how Tempesta FW
handle pipelined response.
> Rework deproxy server to send pipelined responses

- framework/docker_server.py
- helpers/remote.py
Fixed errors: AttributeError: 'LocalNode' object has no attribute 'copy_file_to_node'
> Hot fixes for errors after merged changes in remote.py

- helpers/tf_cfg.py
> Logging: rich handler console width

- helpers/networker.py
- t_stress/test_stress.py
- t_tcp_options/__init__.py
- t_tcp_options/test_tcp_options.py
Add test to check how Tempesta FW works if
`net.ipv4.tcp_mtu_probing` is set
> Add tests to check tcp options

- http2_general/test_h2_frame.py
Set date which will never expired to receive 304 response
> Fix data in test.

- helpers/remote.py
- t_stress/test_ddos.py
related to https://github.com/tempesta-tech/tempesta-ci/pull/34
> fix for SUT

- t_fault_injection/test_fault_injection_base.py
- tests_disabled_tcpseg.json
There was a BUG in Tempesta FW when `tfw_h2_prep_resp-> tfw_h2_frame_local_resp` fails. This error injections tests check it.`
> Implement error injection tests

- README.md
- helpers/tf_cfg.py
- run_tests.py
Related to [PR37](https://github.com/tempesta-tech/tempesta-ci/pull/37)
> add `tests_config.ini` generation for remote setup

- .gitignore
- README.md
- setup.py
A new version of the test environment setup considering the need for a virtual environment.
> feat: A new version of the test environment setup python

- cache/test_cache.py
Tempesta FW should not save 'Age' response header in cache, during saving response in cache. But Tempesta FW should take it into account during satisfying the next request using this saved response. This tests check it.
> Implement tests to check 'Age' header in response

- http2_general/test_h2_hpack.py
Tempesta FW allocates extra memory during hpack decoding from pool. Add test to check how Tempesta FW uses this memory for decoding headers from hpack dynamic table.
> Implement test for hpack decoding

- helpers/deproxy.py
- http2_general/test_h2_hpack.py
Add tests to check how Tempesta FW load method
from hpack dynamic table.
> Add more tests to check hpack

- t_fault_injection/test_fault_injection_base.py
Do not write to /sys/kernel/debug/fail_function/times in hex, because it is decimal.
Add `tearDown` function to FaultInjection classes that allows to call `teardown_fail_function_test` on test fail
> Fix fault injection tests for 6.12.12

- README.md
- helpers/control.py
- helpers/tempesta.py
- run_tests.py
- setup.py
- tests_disabled.json
Remove unnecessary 1sec wait for tfw_logger to start.
> Enable t_clickhouse tests
